### ISSUE TITLE
Client side navigation

### ISSUE THREAD

**Issue by jewell-lgtm** [LorisSigrist/paraglide-sveltekit-example#2]
I installed the project, ran `npm install` `npm start`, and client side navigation appears to be broken.

requests to `localhost:5174/` and `localhost:5174/about/` work as expected, requests via `curl` look like normal sveltekit requests.

However, refreshing the page or clicking on the links result in requests that sveltekit does not handle, eventually timing out (from the client side).

Maybe a version mishmash? If I can help debug in any way, please let me know!

**Comment by LorisSigrist** [comment]
That's very odd, do you have a repository I could take a look at?

**Comment by LorisSigrist** [comment]
I can reproduce this. This repository is auto-synced from opral/monorepo, so there is the possibility that something is going wrong there

**Comment by LorisSigrist** [comment]
Not really sure what's going on TBH. The exact same code does run in opral/monrepo. Might be a case of incompatible dependencies. Will have to look further

**Comment by jewell-lgtm** [comment]
Hi @LorisSigrist  thanks for digging in to this I did do some version mashing to see if it helped but I wasn't able to look into it deeply yet.

I will try and narrow the issue to some of the upstream components and raise an issue there if I find anything

**Comment by LorisSigrist** [comment]
This was most likely caused by https://github.com/vitejs/vite/issues/16245 & will be fixed in the next vite version
